#.github/workflows/deploy.yml

name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
  
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'

defaults:
  run:
    working-directory: ./04-nestjs-rick-and-morty

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test:ci
        
      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}

      - name: Migrate DB
        run: npm run db:migrate -- --config=drizzle-vercel.config.ts

deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-nestjs-rick-and-morty
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm install
        # working-directory: 04-nestjs-rick-and-morty

      - name: Install Vercel CLI
        run: npm add -g vercel@latest
        # working-directory: 04-nestjs-rick-and-morty

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}
        # working-directory: 04-nestjs-rick-and-morty

      - name: Build Project Artifacts
        run: vercel build --prod
        # working-directory: 04-nestjs-rick-and-morty

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
        # working-directory: 04-nestjs-rick-and-morty